<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyName>RobloxManager</AssemblyName>
    <RootNamespace>RobloxManager</RootNamespace>
    <Version>1.0.0</Version>
    <Company>nigMenu</Company>
    <Product>Roblox Manager</Product>
    <Description>Multi-account Roblox instance manager with private server support</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
